// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Client.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Basket
    {
        /// <summary>
        /// Initializes a new instance of the Basket class.
        /// </summary>
        public Basket()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Basket class.
        /// </summary>
        public Basket(System.Guid? id = default(System.Guid?), IList<Item> items = default(IList<Item>), System.Guid? ownerId = default(System.Guid?))
        {
            Id = id;
            Items = items;
            OwnerId = ownerId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public System.Guid? Id { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "items")]
        public IList<Item> Items { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ownerId")]
        public System.Guid? OwnerId { get; private set; }

    }
}
